networks:
  net:
    driver: bridge

volumes:
  postgres_data:

services:
  app:
    build: .
    environment:
      PG_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      RMQ_URL: rabbit://
      CONFIG_PATH: ${CONFIG_PATH}
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    networks:
      - net

  postgres:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}